[cmake]
version = "3.15"
# subdirs = []
# build-dir = ""
# cpp-flags = []
# c-flags = []
# link-flags = []
# generator = ""
# arguments = []

[project]
name = "bfast"
version = "0.1.0"

[find-package]
# LLVM = { version = "12.0", required = true, config = true }

[fetch-content]
# REMILL = { git = "https://github.com/lifting-bits/remill" }

# [options]

[target.bfast]
type = "executable"

sources = [
    "src/**.cpp",
    "include/**.hpp"
]

include-directories = [
    "include"
]

compile-features = ["cxx_std_20"]

compile-definitions = []

link-libraries = [
]

[[install]]
targets = ["bfast"]
destination = "${CMAKE_INSTALL_PREFIX}/bin"
