[cmake]
version = "3.15"
# subdirs = []
# build-dir = ""
# cpp-flags = []
# c-flags = []
# link-flags = []
# generator = ""
# arguments = []

[project]
name = "llvmbf"
version = "0.1.0"

[find-package]
LLVM = { version = "12.0", required = true, config = true }

[fetch-content]
# REMILL = { git = "https://github.com/lifting-bits/remill" }

# [options]

[target.llvmbf]
type = "executable"

sources = [
    "src/**.cpp",
    "include/**.hpp"
]

include-directories = [
    "include"
]

compile-features = ["cxx_std_20"]

compile-definitions = []

link-libraries = [
    "LLVMCore",
    "LLVMCodeGen",
    "LLVMSupport",
    "LLVMLinker",
    "LLVMX86CodeGen",
    "LLVMX86AsmParser",
    "LLVMX86Desc",
    "LLVMX86Disassembler",
    "LLVMX86Info",
    "LLVMAsmParser",
    "LLVMPasses"
]

cmake-after = """
target_include_directories(${PROJECT_NAME} SYSTEM PUBLIC ${LLVM_INCLUDE_DIRS})
"""

[[install]]
targets = ["llvmbf"]
destination = "${CMAKE_INSTALL_PREFIX}/bin"
